<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "diggclonecontentclassespackage",
                     "development" => false,
                     "summary" => "Export of 8 content classes",
                     "description" => "This package contains exported definitions of the following content classes:\n- Folder\n- User\n- Link\n- Story\n- Category\n- Bug Report Form\n- YouTube Video Embed\n- Instagram Video Embed\n",
                     "vendor" => false,
                     "vendor-dir" => false,
                     "priority" => false,
                     "type" => "contentclass",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "6.0.6stable",
                                           "named-version" => "6.0stable" ),
                     "maintainers" => array( array( "name" => "graham",
                                                    "email" => "graham@se7enx.com",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => 1729994053,
                                           "host" => "edit.digg.one",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "data" => "This file is part of the package diggclonecontentclassespackage.\n\nThis package is free software; you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation; either version 2 of the License, or\n(at your option) any later version.\n\nThis package is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this package; if not, write to the Free Software\nFoundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n",
                                                  "audience" => false ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => 1729994053,
                                                  "person" => "graham",
                                                  "email" => "graham@se7enx.com",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array(),
                     "version-number" => "1.0.1",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array( array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "folder" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "user" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "link" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "story" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "category" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "bug_report_form" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "youtube_video" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "instagram_video" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-folder",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-user",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-link",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-story",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-category",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-bug_report_form",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-youtube_video",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-instagram_video",
                                                "sub-directory" => "ezcontentclass" ) ),
                     "uninstall" => array( array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-folder",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-user",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-link",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-story",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-category",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-bug_report_form",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-youtube_video",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-instagram_video",
                                                  "sub-directory" => "ezcontentclass" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages";
?>
