<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "diggclonecontentpackage",
                     "development" => false,
                     "summary" => "login, all, signup, stories, c, about, tools, contact",
                     "description" => "This package contains the following nodes :\nlogin - subtree\nall - subtree\nsignup - subtree\nstories - subtree\nc - subtree\nabout - subtree\ntools - subtree\ncontact - subtree\n",
                     "vendor" => false,
                     "vendor-dir" => false,
                     "priority" => false,
                     "type" => "contentobject",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "6.0.6stable",
                                           "named-version" => "6.0stable" ),
                     "maintainers" => array( array( "name" => "graham",
                                                    "email" => "graham@se7enx.com",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => 1729993546,
                                           "host" => "edit.digg.one",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "data" => "This file is part of the package diggclonecontentpackage.\n\nThis package is free software; you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation; either version 2 of the License, or\n(at your option) any later version.\n\nThis package is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this package; if not, write to the Free Software\nFoundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n",
                                                  "audience" => false ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => 1729993546,
                                                  "person" => "graham",
                                                  "email" => "graham@se7enx.com",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array( "1c685c3edc5f658147445bd9111dbe57" => array( "original-path" => "var/site/storage/images/digg/c/images/book-learning-ez-publish/37858-1-eng-US/book-learning-ez-publish.png",
                                                                                               "package-path" => "simplefiles/952c8ff7.png" ),
                                                  "26fe88bd52c88377fe5bc8d65504d15d" => array( "original-path" => "var/site/storage/images/digg/c/images/ez-publish-6-open-source-cms-banner-2024-09-21-1337/6957-1-eng-US/ez-publish-6-open-source-cms-banner-2024-09-21-1337.jpg",
                                                                                               "package-path" => "simplefiles/184947ea.jpg" ),
                                                  "5718dea185e004ca7a9cae6947d7d63f" => array( "original-path" => "var/site/storage/images/digg/c/images/7x-is-open-source-website-building-platform-experts-call-us-today-blish-6-open-source-cms-banner-2024-09-21-1337/6963-1-eng-US/7x-is-open-source-website-building-platform-experts-call-us-today-blish-6-open-source-cms-banner-2024-09-21-1337.jpg",
                                                                                               "package-path" => "simplefiles/93efc3c3.jpg" ),
                                                  "99baa8dd116353c054f345388ec04ed9" => array( "original-path" => "var/site/storage/images/digg/c/images/kracker-org-preview-box/6981-1-eng-US/kracker-org-preview-box.png",
                                                                                               "package-path" => "simplefiles/3ccd7d22.png" ),
                                                  "2421520ed57f2bd48f5299080fb4d198" => array( "original-path" => "var/site/storage/images/digg/c/images/digg/7119-2-eng-US/digg.webp",
                                                                                               "package-path" => "simplefiles/a9b82c8e.webp" ),
                                                  "65104adc7911c70c21ea46cd0184b138" => array( "original-path" => "var/site/storage/images/digg/c/images/theme/8785-1-eng-US/theme.png",
                                                                                               "package-path" => "simplefiles/2218e29b.png" ),
                                                  "250b7baa6649d8442dff1ad566701824" => array( "original-path" => "var/site/storage/images/digg/c/images/ez-digg/8899-1-eng-US/ez-digg.png",
                                                                                               "package-path" => "simplefiles/f0a44a97.png" ),
                                                  "4287b611fa898c33a38fc6b79639b20b" => array( "original-path" => "var/site/storage/images/media/images/community/digg-logo-1-1/8905-1-eng-US/digg-logo-1-1.png",
                                                                                               "package-path" => "simplefiles/c9240e0c.png" ),
                                                  "12260036df7d1af5d7de5aca386bea9d" => array( "original-path" => "var/site/storage/images/digg/c/images/terracons-logo/9010-1-eng-US/terracons-logo.jpg",
                                                                                               "package-path" => "simplefiles/b740e918.jpg" ),
                                                  "aea958b05b147b86b310cf0bf6a73e3c" => array( "original-path" => "var/site/storage/images/digg/c/images/7x-website-hosting/9151-1-eng-US/7x-website-hosting.png",
                                                                                               "package-path" => "simplefiles/568bba69.png" ),
                                                  "68f487c19189ede3eee3df355cdf42e0" => array( "original-path" => "var/site/storage/images/digg/c/images/sole/9287-1-eng-US/sole.png",
                                                                                               "package-path" => "simplefiles/2863bd4e.png" ) ),
                     "version-number" => "1.0.1",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array( array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "link" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "category" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "folder" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "story" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "comment" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "youtube_video" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "image" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "instagram_video" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "article" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "bug_report_form" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "feedback_form" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-link",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-category",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-folder",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-story",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-comment",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-youtube_video",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-image",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-instagram_video",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-article",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-bug_report_form",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-feedback_form",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentobject",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "contentobjects",
                                                "sub-directory" => "ezcontentobject" ) ),
                     "uninstall" => array( array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-link",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-category",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-folder",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-story",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-comment",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-youtube_video",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-image",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-instagram_video",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-article",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-bug_report_form",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-feedback_form",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentobject",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "contentobjects",
                                                  "sub-directory" => "ezcontentobject" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages";
?>
