{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"Discover the Exponential Platform forums"|i18n("design/standard/setup/init")}
<ul>
  <li><a href="https://share.exponential.earth/forums/Exponential-platform" target="_blank">{"Exponential Platform"|i18n("design/standard/setup/init")}</a></li>
  <li><a href="https://share.exponential.earth/forums/install-configuration" target="_blank">{"Installation & configuration"|i18n("design/standard/setup/init")}</a></li>
  <li><a href="https://share.exponential.earth/forums/setup-design" target="_blank">{"Setup and design"|i18n("design/standard/setup/init")}</a></li>
  <li><a href="https://share.exponential.earth/forums/general" target="_blank">{"General"|i18n("design/standard/setup/init")}</a></li>
</ul>
