{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div align="center" style="padding-top: 0.5em;">
<p class="small" style="color: #ffffff;"><a href="https://exponential.earth">Exponential</a> copyright &copy; 1999-2025 <a href="https://se7enx.com">7x</a></p>
</div>